name: "Deps: Hold Gate"

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  hold:
    uses: arcuru/actions/.github/workflows/dependency-hold.yml@863120f2dbc739f0b9a66c5c01e85b87d7551ac8 # v0.3.1
