name: "Deps: Security Audit"

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  audit:
    uses: arcuru/actions/.github/workflows/security-audit.yml@863120f2dbc739f0b9a66c5c01e85b87d7551ac8 # v0.3.1
